stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker
  services:
    - docker:dind
    - docker/compose:1.23.2
  script:
    - echo $BUILD_VARS | base64 -d > ./.env
    - sh ./scripts/build/build-web-image.sh
    - docker-compose -f ./infrastructure/docker-compose/docker-compose.yml -f ./infrastructure/docker-compose/docker-compose-dev.yml up -d

test_backend:
  stage: test
  script: echo "Running tests"

test_frontend:
  stage: test
  script: echo "Running tests"


deploy_review:
  stage: deploy
  script:
  - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
  - branches
  except:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
