stages:
  - build
  - test
  - release
  - deploy
  - performance

image: docker

build:
  stage: build
  script:
    - sh ./scripts/build/build.sh

test_backend:
  image: tmaier/docker-compose:latest
  services:
   - docker:dind
  stage: test

  script:
    - sh ./scripts/test/test.sh
    - echo "Running backend tests"

test_frontend:
  stage: test
  script:
    - echo "Running tests"

release:
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  stage: release
  script:
    - sh ./scripts/release/release.sh

deploy_review:
  stage: deploy
  script:
    - sh ./scripts/deploy/deploy.sh
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
  - branches
  except:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
