stages:
  - build
  - test
  - release
  - deploy
  - performance

image: tmaier/docker-compose:latest

build:
  stage: build
  services:
    - docker:dind
  script:
    - sh ./scripts/build/build.sh
  artifacts:
    paths:
    - /var/lib/docker/
    expire_in: 1 week

test_backend:
  stage: test

  services:
    - docker:dind
  script:
    - sh ./scripts/test/test.sh
    - echo "Running backend tests"

test_frontend:
  stage: test
  script:
    - echo "Running tests"


release:
  stage: release
  script:
    - sh ./scripts/release/release.sh


deploy_review:
  stage: deploy
  script:
    - sh ./scripts/deploy/deploy.sh
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
  - branches
  except:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
