stages:
  - build
  - test
  - release
  - deploy
  - performance

build:
  stage: build
  script:
    - sh ./scripts/build/build.sh

test_backend:
  stage: test

  before_script:
    - helm init --client-only
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo update

  script:
    - sh ./scripts/test/test.sh
    - echo "Running backend tests"

test_frontend:
  stage: test
  script:
    - echo "Running tests"

release:
  stage: release
  script:
    - sh ./scripts/release/release.sh

deploy_review:
  stage: deploy
  script:
    - sh ./scripts/deploy/deploy.sh
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG-api.powerstack.dev
  only:
  - branches
  except:
  - master

deploy_staging:
  before_script:
    - helm init --client-only
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo update
  stage: deploy
  script:
    - sh ./scripts/deploy/deploy.sh
  environment:
    name: staging
    url: https://staging-api.powerstack.dev
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://api.powerstack.dev
  when: manual
  only:
    - master
