version: '3.3'

services:

  frontend-web:
    image: registry.gitlab.com/travel-nation/power-stack/frontend/web:dev
    entrypoint:
      - sh
      - -c
      - "gatsby build && nginx -g 'daemon off;'"
    env_file:
      - ../../.env
    ports:
      - "8000:80"
      - "8001:443"
    restart: always
    depends_on:
      - backend-web

  backend-web:
    image: registry.gitlab.com/travel-nation/power-stack/backend/web:dev
    env_file:
      - ../../.env
    volumes:
      - web-code:/var/www/:ro
      - web-files:/var/www/web/sites/default/files/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend-php
    extra_hosts:
      - "${API_HOST}:127.0.0.1"

  backend-php:
    image: registry.gitlab.com/travel-nation/power-stack/backend/php:dev
    env_file:
      - ../../.env
    entrypoint:
      - sh
      - -c
      - "composer -n install -vvv && php-fpm"
    ports:
      - "9000"
    volumes:
      - web-code:/var/www/
      - web-files:/var/www/web/sites/default/files/
    restart: always

  backend-db:
    image: postgres:${POSTGRES_VER}
    env_file:
      - ../../.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend-caching:
    image: redis:latest

volumes:
  web-code:
  web-config:
  web-files:
  db-data:
