version: '3.3'

services:

  frontend-web:
    build:
      context: ../../
      dockerfile: ./infrastructure/docker/frontend-web/Dockerfile
      args:
      - NGINX_VER=$NGINX_VER
      - HOST=$HOST
      - ENV=$ENV
      - API_HOST=$API_HOST
    entrypoint:
      - sh
      - -c
      - "npm install && gatsby develop -p 8080 -H 0.0.0.0"
    ports:
      - "8080:8080"
    volumes:
      - ../../frontend-code:/var/www:delegated
    links:
      - "backend-web:${API_HOST}"

  backend-web:
    build:
      context: ../../
      dockerfile: ./infrastructure/docker/backend-web/Dockerfile
      args:
      - NGINX_VER=$NGINX_VER
      - API_HOST=$API_HOST
    volumes:
      - ../../backend-code:/var/www:ro
      - ../../backend-code/web/sites/default/files:/var/www/web/sites/default/files:ro


  backend-php:
    build:
      context: ../../
      dockerfile: ./infrastructure/docker/backend-php/Dockerfile
      args:
      - PHP_VER=$PHP_VER
    entrypoint:
      - sh
      - -c
      - "composer -n update -vvv && php-fpm && drush updb && drush cr"
    volumes:
      - ../../backend-code:/var/www:delegated
      - ../../backend-code/web/sites/default/files:/var/www/web/sites/default/files:delegated
