apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml -c
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-caching
  name: backend-caching-{{ .Release.Name }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend-caching
    spec:
      containers:
      - image: redis:latest
        nodeSelector:
          cloud.google.com/gke-nodepool: pool-1
        name: backend-caching-{{ .Release.Name }}
        resources: {}
      restartPolicy: Always
status: {}
