apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend-web
  name: backend-web
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: backend-web
  type: LoadBalancer
  externalTrafficPolicy: Local
status:
  loadBalancer: {}
