apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml -c
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    app: backend-db-{{ .Release.Name }}
  name: backend-db-{{ .Release.Name }}
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: backend-db-{{ .Release.Name }}
  type: LoadBalancer
  sessionAffinity: ClientIP