apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml -c
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-web
  name: frontend-web
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  - name: "8001"
    port: 8001
    targetPort: 443
  selector:
    io.kompose.service: frontend-web
    app: frontend-web
status:
  loadBalancer: {}
