{{ if .Values.GKE }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-{{ .Release.Name }}
  template:
    metadata:
      labels:
        role: nfs-server-{{ .Release.Name }}
    spec:
      containers:
      - name: nfs-server-{{ .Release.Name }}
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/www/web/sites/default/files/
            name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: regional-pvc-{{ .Release.Name }}
            fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regionalpd-storageclass-{{ .Release.Name }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: europe-west2-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regional-pvc-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: regionalpd-storageclass-{{ .Release.Name }}
{{ end }}